RGP/LandManager/Controllers/LandParcelController.cs
using Microsoft.AspNetCore.Mvc;
using LandManager.Models;
using LandManager.Core;

namespace LandManager.Controllers
{
    public class LandParcelController : Controller
    {
        private readonly ILandParcelService _landParcelService;

        public LandParcelController(ILandParcelService landParcelService)
        {
            _landParcelService = landParcelService;
        }

        public async Task<IActionResult> Index()
        {
            var landParcels = await _landParcelService.GetAllAsync();
            return View("~/Views/Home/LandParcelList.cshtml", landParcels);
        }
        public IActionResult Create()
        {
            return View();
        }

        // POST: /LandParcel/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TotalAreaInHectares, SurveyDate, LandPropertyId")] LandParcel landParcel)
        {
            await _landParcelService.AddAsync(landParcel);
            return RedirectToAction(nameof(Index));
        }

        // GET: /LandParcel/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landParcel = await _landParcelService.GetByIdAsync(id.Value);
            if (landParcel == null)
            {
                return NotFound();
            }
            return View(landParcel);
        }

        // POST: /LandParcel/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LandParcelId, TotalAreaInHectares, SurveyDate, LandPropertyId")] LandParcel landParcel)
        {
            if (id != landParcel.LandParcelId)
            {
                return NotFound();
            }

            {
                try
                {
                    await _landParcelService.UpdateAsync(landParcel);
                }
                catch
                {
                    if (!await LandParcelExists(id))
                    {
                        return NotFound();
                    }
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: /LandParcel/Delete/1
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landParcel = await _landParcelService.GetByIdAsync(id.Value);
            if (landParcel == null)
            {
                return NotFound();
            }

            return View(landParcel);
        }

        // POST: /LandParcel/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _landParcelService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> LandParcelExists(int id)
        {
            var landParcel = await _landParcelService.GetByIdAsync(id);
            return landParcel != null;
        }

        // GET: /LandParcel/Details/1
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landParcel = await _landParcelService.GetByIdAsync(id.Value);
            if (landParcel == null)
            {
                return NotFound();
            }

            return View(landParcel);
        }
    }
}

RGP/LandManager/Controllers/LandPropertyController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LandManager.Models;
using LandManager.Service.Implementations;
using LandManager.Core;
using Microsoft.EntityFrameworkCore;

namespace LandManager.Controllers
{
    public class LandPropertyController : Controller
    {
        private readonly ILandPropertyService _landPropertyService;

        public LandPropertyController(ILandPropertyService landPropertyService)
        {
            _landPropertyService = landPropertyService;
        }

        public async Task<IActionResult> Index()
        {
            var landProperties = await _landPropertyService.GetAllAsync();
            return View("~/Views/Home/PropertyList.cshtml", landProperties);
        }

        public IActionResult Create()
        {
            return View();
        }

        // POST: /LandProperty/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name, CadastreNumber, Status, OwnerId")] LandProperty landProperty)
        {
            await _landPropertyService.AddAsync(landProperty);
            return RedirectToAction(nameof(Index));
        }

        // GET: /LandProperty/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landProperty = await _landPropertyService.GetByIdAsync(id.Value);
            if (landProperty == null)
            {
                return NotFound();
            }
            return View(landProperty);
        }

        // POST: /LandProperty/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LandPropertyId, Name, CadastreNumber, Status, OwnerId")] LandProperty landProperty)
        {
            if (id != landProperty.LandPropertyId)
            {
                return NotFound();
            }
                try
                {
                    await _landPropertyService.UpdateAsync(landProperty);
                }
                catch
                {
                    if (!await LandPropertyExists(id))
                    {
                        return NotFound();
                    }
                    throw;
                }
                return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landProperty = await _landPropertyService.GetByIdWithLandParcelsAsync(id.Value);

            if (landProperty == null)
            {
                return NotFound();
            }

            return View(landProperty);
        }

        // GET: /LandProperty/Delete/1
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landProperty = await _landPropertyService.GetByIdAsync(id.Value);
            if (landProperty == null)
            {
                return NotFound();
            }

            return View(landProperty);
        }

        // POST: /LandProperty/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _landPropertyService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> LandPropertyExists(int id)
        {
            var landProperty = await _landPropertyService.GetByIdAsync(id);
            return landProperty != null;
        }
    }
}

RGP/LandManager/Controllers/LandUseController.cs
using Microsoft.AspNetCore.Mvc;
using LandManager.Models;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using LandManager.Core;

namespace LandManager.Controllers
{
    public class LandUseController : Controller
    {
        private readonly ILandUseService _landUseService;

        public LandUseController(ILandUseService landUseService)
        {
            _landUseService = landUseService;
        }

        public async Task<IActionResult> Index()
        {
            var landUses = await _landUseService.GetAllAsync();
            return View("~/Views/Home/LandUsageList.cshtml", landUses);
        }

        // GET: /LandUse/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: /LandUse/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Type,AreaInHectares,LandParcelId")] LandUse landUse)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _landUseService.AddAsync(landUse);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException ex)
            {
                // Log the error (uncomment ex variable name and write a log.)
                ModelState.AddModelError("", "Neizdevās saglabāt izmaiņas. " +
                                             "Mēģiniet vēlreiz, un, ja problēma atkārtojas, " +
                                             "lūdzu, sazinieties ar sistēmas administratoru.");
            }

            return View(landUse);
        }

        // GET: /LandUse/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var landUse = await _landUseService.GetByIdAsync(id);
            if (landUse == null)
            {
                return NotFound();
            }
            return View(landUse);
        }

        // POST: /LandUse/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LandUseId,Type,AreaInHectares,LandParcelId")] LandUse landUse)
        {
            if (id != landUse.LandUseId)
            {
                return NotFound();
            }

            try
            {
                await _landUseService.UpdateAsync(landUse);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                // Log the error and display a relevant message to the user
            }

            return View(landUse);
        }

        // GET: /LandUse/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var landUse = await _landUseService.GetByIdAsync(id);
            if (landUse == null)
            {
                return NotFound();
            }
            return View(landUse);
        }

        // POST: /LandUse/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _landUseService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        // GET: /LandUse/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var landUse = await _landUseService.GetByIdAsync(id.Value);
            if (landUse == null)
            {
                return NotFound();
            }

            return View(landUse);
        }
    }
}

RGP/LandManager/Controllers/PersonController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using LandManager.Models;
using Microsoft.AspNetCore.Authorization;
using LandManager.Core;

namespace LandManager.Controllers
{
  
    public class PersonController : Controller
    {
        private readonly IPersonService _personService;

        public PersonController(IPersonService personService)
        {
            _personService = personService;
        }

        public async Task<IActionResult> Index(string searchString)
        {
            var persons = string.IsNullOrEmpty(searchString)
                          ? await _personService.GetAllAsync()
                          : await _personService.SearchAsync(searchString);

            return View("~/Views/Home/PersonList.cshtml", persons);
        }

        // GET: /Person/Create
        public IActionResult Create()
        {
            return View(new Person()); // Jauns tukšs Person objekts veidlapai
        }

        // POST: /Person/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Person person)
        {
            try
            {
                await _personService.AddAsync(person);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Notika kļūda saglabājot datus: " + ex.Message);
            }

            return View(person);
        }

        // GET: /Person/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _personService.GetByIdAsync(id.Value);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: /Person/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PersonId, FirstName, LastNameOrTitle, PersonalCodeOrRegistrationNumber, Type")] Person person)
        {
            if (id != person.PersonId)
            {
                return NotFound();
            }

            try
            {
                await _personService.UpdateAsync(person);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                if (!await PersonExists(id))
                {
                    return NotFound();
                }
                throw;
            }

            // Ja kļūda nav notikusi, tad nevajag pārbaudīt ModelState un atgriezt View(person)
        }

        // GET: /Person/Details/1
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var summaryViewModel = await _personService.GetSummaryViewModelAsync(id.Value);
            if (summaryViewModel == null)
            {
                return NotFound();
            }

            return View(summaryViewModel);
        }

        // GET: /Person/Delete/1
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _personService.GetByIdAsync(id.Value);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: /Person/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _personService.GetByIdAsync(id);
            if (person != null)
            {
                await _personService.DeleteAsync(id);
            }
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> PersonExists(int id)
        {
            var person = await _personService.GetByIdAsync(id);
            return person != null;
        }
    }
}

RGP/LandManager/Views/Person/Create.cshtml
@model LandManager.Models.Person

@{
    ViewData["Title"] = "Pievienot Personu";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Vārds</label>
        <input asp-for="FirstName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label">Uzvārds</label>
        <input asp-for="LastName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Title" class="control-label">Nosaukums</label>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="PersonalCodeOrRegistrationNumber" class="control-label">Personas Kods vai Reģistrācijas Nr</label>
        <input asp-for="PersonalCodeOrRegistrationNumber" class="form-control" />
        <span asp-validation-for="PersonalCodeOrRegistrationNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type" class="control-label">
            Fiziska vai juridiska.
        </label>
        <input asp-for="Type" class="form-control" />
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Saglabāt" class="btn btn-primary" />
    </div>
</form>

RGP/LandManager/Views/Person/Delete.cshtml
@model LandManager.Models.Person

@{
    ViewData["Title"] = "Dzēst Personu";
}

<h2>@ViewData["Title"]</h2>

<h3>Vai esat pārliecināts, ka vēlaties dzēst šo personu?</h3>
<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalCodeOrRegistrationNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PersonalCodeOrRegistrationNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>

    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="PersonId" />
        <input type="submit" value="Dzēst" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Atcelt</a>
    </form>
</div>

RGP/LandManager/Views/Person/Details.cshtml
@model LandManager.Models.SummaryViewModel

@{
    ViewData["Title"] = "Personas Detaļas";
}

<h2>@ViewData["Title"]</h2>

@foreach (var person in Model.Persons)
{
    <div>
        <h3>@person.FirstName @person.LastName</h3>
        <p>Personas Kods: @person.PersonalCodeOrRegistrationNumber</p>
        <p>Tipa: @person.Type</p>
    </div>
}

<h3>Īpašumi</h3>
@foreach (var property in Model.LandProperties)
{
    <p>
        @property.Name - @property.CadastreNumber
        <a asp-controller="LandProperty" asp-action="Details" asp-route-id="@property.LandPropertyId">Skatīt detaļas</a>
    </p>
}

<h3>Zemes Gabali</h3>
@foreach (var parcel in Model.LandParcels)
{
    <p>
        Total Area: @parcel.TotalAreaInHectares hectares
        <a asp-controller="LandParcel" asp-action="Details" asp-route-id="@parcel.LandParcelId">Skatīt detaļas</a>
    </p>
}

<h3>Zemes Lietojumi</h3>
@foreach (var use in Model.LandUses)
{
    <p>
        @use.Type - @use.AreaInHectares hectares
        <a asp-controller="LandUse" asp-action="Details" asp-route-id="@use.LandUseId">Skatīt detaļas</a>
    </p>
}
<div>
    <button onclick="history.back()" class="btn btn-secondary">Atpakaļ</button>
</div>

RGP/LandManager/Views/Person/Edit.cshtml
@model LandManager.Models.Person

@{
    ViewData["Title"] = "Rediģēt Personu";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="PersonId" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Vārds</label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName" class="control-label">Uzvārds</label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Title" class="control-label">Nosaukums</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PersonalCodeOrRegistrationNumber" class="control-label">Personas Kods vai Reģistrācijas Nr</label>
        <input asp-for="PersonalCodeOrRegistrationNumber" class="form-control" />
        <span asp-validation-for="PersonalCodeOrRegistrationNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type" class="control-label">Tipa</label>
        <input asp-for="Type" class="form-control" />
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Saglabāt Izmaiņas" class="btn btn-primary" />
    </div>
</form>